# Label by branch name
feature:
  - head-branch: ['^feat/', '^feature/']

bugfix:
  - head-branch: ['^fix/', '^bugfix/']

documentation:
  - head-branch: ['^docs/']

chore:
  - head-branch: ['^chore/']

# Label by changed files
components:
  - changed-files:
      - any-glob-to-any-file: 'src/components/**'

config:
  - changed-files:
      - any-glob-to-any-file: ['*.config.*', 'tsconfig.*', '.eslintrc*']

tests:
  - changed-files:
      - any-glob-to-any-file: 'src/**/*.test.*'

ai-rules:
  - changed-files:
      - any-glob-to-any-file: ['.claude/**', 'CLAUDE.md', '.cursorrules']

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
